let ws, roomId, state, playerId, role, submittedRoundId = null, leaderboardOpen = false;
const app = document.querySelector("#app"), query = new URLSearchParams(location.search);
const esc = value => String(value ?? "").replace(/[&<>\"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));
const clock = (seconds, display) => { if (display) return display; const s = Math.max(0, Math.floor(seconds || 0)); return `${String(Math.floor(s / 60)).padStart(2,"0")}:${String(s % 60).padStart(2,"0")}`; };
const send = message => { if (ws?.readyState === 1) ws.send(JSON.stringify(message)); };

async function getFixtures() {
  const response = await fetch(`/api/live-fixtures`);
  const data = await response.json(); if (!response.ok) throw Error(data.error || "Fixtures unavailable"); return data;
}
const competitionNames = { "eng.1":"Premier League", "eng.2":"Championship", "sco.1":"Scottish Premiership", "esp.1":"LaLiga", "ger.1":"Bundesliga", "ita.1":"Serie A", "fra.1":"Ligue 1", "usa.1":"MLS", "aus.1":"A-League Men" };
const competitionName = fixture => fixture.competition || competitionNames[fixture.league] || fixture.league || "Competition";
const scheduledTime = value => value ? new Intl.DateTimeFormat("en-GB", { day:"2-digit", month:"2-digit", year:"2-digit", hour:"2-digit", minute:"2-digit", hour12:false }).format(new Date(value)).replace(",", "") : "Scheduled";
function fixtureCard(f) {
  const live = f.state === "in";
  return `<article class="fixture-choice" data-fixture="${esc(f.id)}" data-sport="${esc(f.sport || "soccer")}" data-league="${esc(f.league || "eng.1")}"><button class="fixture-open" type="button"><span class="fixture-teams"><strong>${esc(f.home.name)}</strong><b>${f.home.score ?? "–"} — ${f.away.score ?? "–"}</b><strong>${esc(f.away.name)}</strong></span><small class="fixture-status ${live ? "live" : ""}">${esc(live ? "LIVE NOW" : scheduledTime(f.date))} · ${esc(competitionName(f))} ${f.venue ? ` · ${esc(f.venue)}` : ""}</small></button>${live ? "" : `<button class="reminder" type="button" data-reminder="${esc(f.id)}" aria-label="Add ${esc(f.home.name)} v ${esc(f.away.name)} to calendar" title="Add to calendar"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3v3m10-3v3M4.5 9.5h15M6 5h12a2 2 0 0 1 2 2v11.5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z"/></svg></button>`}</article>`;
}
function calendarStamp(value) { return new Date(value).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z"); }
function icsText(value) { return String(value).replace(/[\\;,]/g, match => `\\${match}`).replace(/\r?\n/g, "\\n"); }
async function addReminder(fixture) { const start = new Date(fixture.date), end = new Date(start.getTime() + 2 * 60 * 60 * 1000), title = `${fixture.home.name} v ${fixture.away.name} · Called It`, joinUrl = `${location.origin}/play`; const ics = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//Called It//Live Matchday//EN", "X-WR-CALNAME:Called It Live Matchday", "BEGIN:VEVENT", `UID:called-it-${fixture.id}@called-it`, `DTSTAMP:${calendarStamp(new Date())}`, `DTSTART:${calendarStamp(start)}`, `DTEND:${calendarStamp(end)}`, `SUMMARY:${icsText(title)}`, `DESCRIPTION:${icsText(`Called It live play-along\\nJoin before kick-off: ${joinUrl}\\nMake your calls, follow the match and see who really knows the game.`)}`, `LOCATION:${icsText("Called It · Live Matchday")}`, "CATEGORIES:Called It,Live Matchday,Football", `URL:${joinUrl}`, "BEGIN:VALARM", "TRIGGER:-PT15M", "ACTION:DISPLAY", "DESCRIPTION:Called It starts in 15 minutes", "END:VALARM", "END:VEVENT", "END:VCALENDAR"].join("\r\n"); const file = new File([ics], `called-it-${fixture.id}.ics`, { type:"text/calendar" }); try { const canUseNativeShare = navigator.share && (!navigator.canShare || navigator.canShare({ files:[file] })); if (canUseNativeShare) { await navigator.share({ title, text:"Add this Called It match to your calendar", files:[file] }); return; } } catch (error) { if (error.name === "AbortError") return; } const link = document.createElement("a"); link.href = URL.createObjectURL(file); link.download = file.name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
async function bootLanding() {
  app.innerHTML = '<header class="brand"><img src="assets/called-it-wordmark.png" alt="Called It"><span class="room">LIVE MATCHDAY</span></header><div class="eyebrow">LIVE GAMES · THE MATCHDAY EDITION</div><h1>Pick a fixture.<br><i>Call it live.</i></h1><p class="muted">These are live or imminent matches. Join before kick-off and make your calls while the game unfolds.</p><section class="card"><div class="section-head"><h2>Live Now</h2><span class="live-list-status"><span class="live-dot"></span>LIVE</span></div><div id="fixtures"><p class="muted">Loading this week’s live games…</p></div></section><p class="fine-print">No host. No private room to create. The fixture is the room.</p>';
  async function load() { const target = document.querySelector("#fixtures"); target.innerHTML = '<p class="muted">Checking the fixture list…</p>'; try { const data = await getFixtures(); const available = (data.fixtures || []).filter(f => { const coverageKey = `${f.sport || "soccer"}:${f.league}`; const coverage = data.leagueCoverage?.[coverageKey] || data.leagueCoverage?.[f.league]; return (f.state === "in" || f.state === "pre") && coverage?.approved === true; }); if (!available.length) { target.innerHTML = '<p class="muted">There are no supported fixtures live or scheduled today.</p>'; return; } const live = available.filter(f => f.state === "in"), upcoming = available.filter(f => f.state !== "in"), hierarchy = ["eng.1", "eng.2", "sco.1", "esp.1", "ger.1", "ita.1", "fra.1", "usa.1", "aus.1", "3"], competitions = [...new Map(available.map(f => [competitionName(f), f.competition || f.league])).entries()].sort((a, b) => (hierarchy.indexOf(a[1]) === -1 ? 999 : hierarchy.indexOf(a[1])) - (hierarchy.indexOf(b[1]) === -1 ? 999 : hierarchy.indexOf(b[1]))); const section = (title, fixtures, empty) => fixtures.length ? `<section class="fixture-group"><h3>${title}</h3>${fixtures.map(fixtureCard).join("")}</section>` : (empty ? `<section class="fixture-group"><h3>${title}</h3><p class="muted">${empty}</p></section>` : ""); target.innerHTML = `<div class="comp-filters"><button class="selected" data-comp-filter="">All competitions</button>${competitions.map(([label, key]) => `<button data-comp-filter="${esc(key)}">${esc(label)}</button>`).join("")}</div><div id="fixture-list">${section("Live now", live, "No supported matches are live right now.")}${section("Upcoming", upcoming, "No upcoming supported fixtures.")}</div>`; const renderList = filter => { document.querySelectorAll("#fixture-list [data-fixture]").forEach(card => { const f = available.find(item => item.id === card.dataset.fixture); card.hidden = Boolean(filter && (f.competition || f.league) !== filter); card.querySelector(".fixture-open")?.addEventListener("click", () => joinFixture(f, card.dataset.league)); card.querySelector("[data-reminder]")?.addEventListener("click", event => { event.stopPropagation(); addReminder(f); }); }); }; document.querySelectorAll("[data-comp-filter]").forEach(button => button.onclick = () => { document.querySelectorAll("[data-comp-filter]").forEach(item => item.classList.toggle("selected", item === button)); renderList(button.dataset.compFilter); }); renderList(""); } catch (error) { target.innerHTML = `<p class="error">${esc(error.message)}</p>`; } }
  await load();
}
async function joinFixture(fixture, league) {
  if (!fixture) return;
  const button = document.querySelector(`[data-fixture="${CSS.escape(fixture.id)}"] .fixture-open`); if (button) button.disabled = true;
  try { const response = await fetch("/api/room/fixture", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ fixture, sport: fixture.sport || "soccer", league, mode:"live" }) }); const data = await response.json(); if (!response.ok) throw Error(data.error || "Could not open fixture"); location.href = `/play?room=${encodeURIComponent(data.roomId)}`; } catch (error) { if (button) button.disabled = false; alert(error.message); }
}
function connect() { ws = new WebSocket(`${location.protocol === "https:" ? "wss" : "ws"}://${location.host}/api/room/${roomId}`); ws.onmessage = event => { const message = JSON.parse(event.data); if (message.type === "identity") { playerId = message.playerId; localStorage.setItem(`calledItPlayer:${roomId}`, playerId); } if (message.state) { state = message.state; render(); } }; ws.onclose = () => setTimeout(connect, 1500); }
function preMatchCard(me) {
  const questions = state.preMatch || [], answered = state.playerStatus?.[playerId] || [], current = questions.find(q => !answered.includes(q.id) && !q.settled);
  if (!current) return '<div class="pre-complete">Your three calls are in. Stay with the match — the next live question will appear here.</div>';
  const answerUi = current.input ? `<label class="number-call">${esc(current.input.suffix)}<input id="preNumber" type="number" min="${current.input.min}" max="${current.input.max}" step="${current.input.step}" value="${current.input.min}"></label><button class="answer" data-pre-submit="${esc(current.id)}">Submit call</button>` : `<div class="answers">${current.choices.map(a => `<button class="answer" data-pre="${esc(a.key)}">${esc(a.label)}</button>`).join("")}</div>`;
  return `<div class="pre-modal-backdrop"><div class="pre-modal"><div class="phase">Your pre-match calls · ${answered.length + 1} of ${questions.length}</div><h2>${esc(current.question)}</h2><p class="muted">Make your call before kick-off.</p>${answerUi}</div></div>`;
}
function simulationPanel() {
  if (role !== "host" || state.mode !== "simulation") return "";
  const s = state.session, paused = s.manualPaused, held = s.holding && s.round?.status === "voting";
  const status = s.status === "lobby" ? "Ready to start" : paused ? "Playback paused" : held ? "Paused for voting" : `Running · ${s.speed || 1}×`;
  const action = paused ? "resume" : "pause";
  return `<section class="card sim-controls"><div class="section-head"><h2>Replay controls</h2><span class="muted">${status}</span></div>${s.status === "lobby" ? `<button data-sim-action="start">Start simulation</button>` : `<button class="secondary" data-sim-action="${action}" ${held ? "disabled" : ""}>${paused ? "Resume playback" : "Pause playback"}</button><div class="sim-speeds"><span class="muted">Speed</span>${[1,2,5,10,20,50].map(speed => `<button class="${Number(s.speed) === speed ? "selected" : ""}" data-sim-speed="${speed}">${speed}×</button>`).join("")}</div>`}<p class="muted sim-note">This controls the shared simulated match clock for every connected player.</p></section>`;
}
function render() {
  if (!state) return;
  const existingFeed = document.querySelector(".broadcast-feed-list"), feedWasNearTop = !existingFeed || existingFeed.scrollTop < 40, feedScrollTop = existingFeed?.scrollTop || 0;
  const f = state.fixture || { home:{name:"Home"}, away:{name:"Away"} }, r = state.session?.round, me = (state.players || []).find(p => p.id === playerId), answered = state.playerStatus?.[playerId] || [], incomplete = (state.preMatch || []).some(q => !answered.includes(q.id) && !q.settled);
  if (submittedRoundId && submittedRoundId !== r?.id) submittedRoundId = null;
  const fixtureStatus = String(state.fixture?.status || "Fixture room"), isHalfTime = /half[\s-]?time|end of (the )?1st half/i.test(fixtureStatus), statusIncludesClock = /\b\d{1,3}(?::\d{2}|\+\d{1,2})/.test(fixtureStatus), matchStatus = isHalfTime ? "HALF-TIME" : statusIncludesClock ? "LIVE" : fixtureStatus;
  const now = Date.now(), remaining = r?.status === "voting" && r.voteEndsAt ? Math.max(0, Math.ceil((r.voteEndsAt - now) / 1000)) : 0, voteLabel = r?.status === "voting" && r.voteEndsAt && state.session?.mode === "simulation" ? `${remaining}s` : "";
  const join = !me ? `<input id="name" placeholder="Your name" maxlength="20"><button id="join">Join match</button>` : `<p class="joined">Joined as <b>${esc(me.name)}</b></p>`;
  const callLocked = Boolean(me && !incomplete && submittedRoundId && submittedRoundId === r?.id);
  const liveEvents = (state.timeline || []).slice().sort((a, b) => (b.offset || 0) - (a.offset || 0));
  const feed = liveEvents.length ? liveEvents.map(e => { const eventText = e.type === "corner" && e.team ? `Corner awarded to ${e.team}` : (e.text || "Live event"); return `<div class="broadcast-event"><span class="event-minute">${e.minute != null ? `${e.minute}'` : "—"}</span><span><b>${esc(eventText)}</b><small>${esc(String(e.type || "event").replaceAll("-", " "))}</small></span></div>`; }).join("") : '<p class="muted">Waiting for the first live match update…</p>';
  const call = callLocked ? '<div class="call-locked"><span class="lock-dot"></span><b>CALL LOCKED IN</b><span>Stay with the match — the next call will land here.</span></div>' : me && !incomplete && r?.status === "voting" ? `<div class="call-modal-backdrop"><section class="call-modal" role="dialog" aria-label="Make your call"><div class="live-kicker"><span class="live-dot"></span>CALL NOW <span class="countdown">${voteLabel}</span></div><h2>${esc(r.question)}</h2><p>Make your call. It stays open until the match answers it.</p><div class="answers">${(r.choices || []).map((a, index) => `<button class="answer" data-answer="${esc(a.key)}"><span class="answer-index">${String.fromCharCode(65 + index)}</span>${esc(a.label)}</button>`).join("")}</div></section></div>` : '';
  const leaderboard = `<div class="leaderboard-modal-backdrop" data-leaderboard-close><section class="leaderboard-modal" role="dialog" aria-modal="true" aria-label="Match leaderboard"><div class="section-head"><h2>Leaderboard</h2><button class="modal-close" data-leaderboard-close aria-label="Close leaderboard">×</button></div><p class="muted">This fixture</p><div class="leaders">${(state.leaderboard || []).map(p => `<div><b>#${p.rank} ${esc(p.name)}</b><span>${p.points} pts · ${p.rounds} calls</span></div>`).join("") || '<p class="muted">No players yet.</p>'}</div></section></div>`;
  const playerStats = me ? `<div class="player-stats"><div class="stats-heading"><span>Your match</span><small>${esc(me.name)}</small></div><div class="stat-tile"><b>${me.points || 0}</b><small>POINTS</small></div><div class="stat-tile"><b>${me.calls ?? me.rounds ?? 0}</b><small>CALLS MADE</small></div><div class="stat-tile"><b>${me.correct || 0}</b><small>CORRECT</small></div></div>` : '';
  app.innerHTML = `<header class="brand"><img src="assets/called-it-wordmark.png" alt="Called It"><span class="room">${esc(state.session?.status || "LIVE")}</span></header><div class="eyebrow-row"><div class="eyebrow">LIVE MATCHDAY</div><button class="leaderboard-trigger" data-leaderboard-open>Leaderboard <span>↗</span></button></div><div class="match-header ${isHalfTime ? "at-half-time" : ""}"><h1>${esc(f.home?.name)} <i>${f.home?.score ?? "–"} — ${f.away?.score ?? "–"}</i> ${esc(f.away?.name)}</h1><p><strong class="match-status">${esc(matchStatus)}</strong> <span>·</span> match clock <b>${clock(state.session?.clock, state.session?.clockDisplay)}</b></p></div>${playerStats}<section class="card broadcast-feed" aria-live="polite"><div class="section-head"><h2>Match feed</h2><span class="feed-live"><span class="live-dot"></span>LIVE</span></div><div class="broadcast-feed-list">${feed}</div></section><footer class="called-it-footer"><img src="assets/called-it-wordmark.png" alt="Called It"><span>Live matchday play-along</span></footer>${simulationPanel()}${state.session?.status === "lobby" ? `<section class="card"><h2>Join this match</h2>${join}<p class="muted">${state.players?.length || 0} supporter(s) are in the room.</p></section>` : ""}${me && incomplete ? preMatchCard(me) : ""}${me && !incomplete ? call : ""}${leaderboardOpen ? leaderboard : ""}`;
  const newFeed = document.querySelector(".broadcast-feed-list"); if (newFeed) { newFeed.scrollTop = feedWasNearTop ? 0 : feedScrollTop; }
  const joinButton = document.querySelector("#join"); if (joinButton) joinButton.onclick = () => { const name = document.querySelector("#name").value || "Supporter"; joinButton.disabled = true; send({type:"join", name, playerId}); };
  document.querySelectorAll("[data-pre]").forEach(button => button.onclick = () => { const q = (state.preMatch || []).find(item => item.choices.some(a => a.key === button.dataset.pre) && !(state.playerStatus?.[playerId] || []).includes(item.id)); send({type:"prematch", playerId, questionId:q?.id, answer:button.dataset.pre}); });
  document.querySelectorAll("[data-pre-submit]").forEach(button => button.onclick = () => send({type:"prematch", playerId, questionId:button.dataset.preSubmit, answer:document.querySelector("#preNumber")?.value}));
  document.querySelectorAll("[data-answer]").forEach(button => button.onclick = () => { button.disabled = true; submittedRoundId = r?.id || null; send({type:"predict", playerId, roundId:r?.id, answer:button.dataset.answer}); render(); });
  document.querySelectorAll("[data-sim-action]").forEach(button => button.onclick = () => { if (button.dataset.simAction === "start") send({type:"start"}); else send({type:"simulation-control", action:button.dataset.simAction}); });
  document.querySelectorAll("[data-sim-speed]").forEach(button => button.onclick = () => send({type:"simulation-control", action:"speed", speed:Number(button.dataset.simSpeed)}));
  document.querySelectorAll("[data-leaderboard-open]").forEach(button => button.onclick = () => { leaderboardOpen = true; render(); });
  document.querySelectorAll("[data-leaderboard-close]").forEach(button => button.onclick = event => { if (event.target === button || button.classList.contains("modal-close")) { leaderboardOpen = false; render(); } });
  if (leaderboardOpen) document.addEventListener("keydown", event => { if (event.key === "Escape") { leaderboardOpen = false; render(); } }, { once:true });
  if (r?.status === "voting") setTimeout(render, 1000);
}
roomId = query.get("room"); role = query.get("role") || "player";
if (roomId) { playerId = localStorage.getItem(`calledItPlayer:${roomId}`); connect(); } else bootLanding();
